def file_create():
    #Create the File
    print('Creating File... Do not close the window')
    global file
    file = open(Name + '.py','w+')
    file.write('#Name' + '\n')
    file.write(Name + '\n')
    file.write('#Password' + '\n')
    file.write(password + '\n')
    file.write('#Boon' + '\n')
    file.write(Boon + '\n')
    file.write('#Bane' + '\n')
    file.write(Bane + '\n')
    file.write('#Level' + '\n')
    file.write(str(LV) + '\n')
    file.write('#HP' + '\n')
    file.write(str(HP) + '\n')
    file.write('#STR' + '\n')
    file.write(str(STR) + '\n')
    file.write('#MAG' + '\n')
    file.write(str(MAG) + '\n')
    file.write('#SKL' + '\n')
    file.write(str(SKL) + '\n')
    file.write('#SPD' + '\n')
    file.write(str(SPD) + '\n')
    file.write('#LCK' + '\n')
    file.write(str(LCK) + '\n')
    file.write('#DEF' + '\n')
    file.write(str(DEF) + '\n')
    file.write('#RES' + '\n')
    file.write(str(RES) + '\n')
    file.write('#HP GROWTH' + '\n')
    file.write(str(HP_GROWTH) + '\n')
    file.write('#STR GROWTH' + '\n')
    file.write(str(STR_GROWTH) + '\n')
    file.write('#MAG GROWTH' + '\n')
    file.write(str(MAG_GROWTH) + '\n')
    file.write('#SKL GROWTH' + '\n')
    file.write(str(SKL_GROWTH) + '\n')
    file.write('#SPD GROWTH' + '\n')
    file.write(str(SPD_GROWTH) + '\n')
    file.write('#LCK GROWTH' + '\n')
    file.write(str(LCK_GROWTH) + '\n')
    file.write('#DEF GROWTH' + '\n')
    file.write(str(DEF_GROWTH) + '\n')
    file.write('#RES GROWTH' + '\n')
    file.write(str(RES_GROWTH) + '\n')
    file.write('#Gold' + '\n')
    file.write(str(GOLD) + '\n')
    file.write('#EXP' + '\n')
    file.write(str(EXP) + '\n')
    file.write('#Sword Rank' + '\n')
    file.write(str(sword_rank) + '\n')
    file.write('#Lance Rank' + '\n')
    file.write(str(lance_rank) + '\n')
    file.write('#Axe Rank' + '\n')
    file.write(str(axe_rank) + '\n')
    file.write('#Bow Rank' + '\n')
    file.write(str(bow_rank) + '\n')
    file.write('#Dagger Rank' + '\n')
    file.write(str(dagger_rank) + '\n')
    file.write('#Fire Rank' + '\n')
    file.write(str(fire_rank) + '\n')
    file.write('#Thunder Rank' + '\n')
    file.write(str(thunder_rank) + '\n')
    file.write('#Wind Rank' + '\n')
    file.write(str(wind_rank) + '\n')
    file.write('#Light Rank' + '\n')
    file.write(str(light_rank) + '\n')
    file.write('#Dark Rank' + '\n')
    file.write(str(dark_rank) + '\n')
    file.write('#Weapon Name' + '\n')
    file.write(weapon_name + '\n')
    file.write('#Weapon Rank' + '\n')
    file.write(weapon_rank + '\n')
    file.write('#Weapon Might' + '\n')
    file.write(weapon_MT + '\n')
    file.write('#Weapon Weight' + '\n')
    file.write(weapon_WT + '\n')
    file.write('#Weapon Hit' + '\n')
    file.write(weapon_HIT + '\n')
    file.write('#Weapon Crit' + '\n')
    file.write(weapon_CRIT + '\n')
    file.write('#Weapon Price' + '\n')
    file.write(weapon_price + '\n')
    file.write('#Weapon EXP' + '\n')
    file.write(weapon_exp + '\n')
    file.write('#Weapon Type' + '\n')
    file.write(weapon_type + '\n')
    file.write('#Weapon Skill' + '\n')
    file.write(weapon_skill + '\n')
    
    
    file.close

    file = open(Name + '.py','w+')
    file.write('#Name' + '\n')
    file.write(Name + '\n')
    file.write('#Password' + '\n')
    file.write(password + '\n')
    file.write('#Boon' + '\n')
    file.write(Boon + '\n')
    file.write('#Bane' + '\n')
    file.write(Bane + '\n')
    file.write('#Level' + '\n')
    file.write(str(LV) + '\n')
    file.write('#HP' + '\n')
    file.write(str(HP) + '\n')
    file.write('#STR' + '\n')
    file.write(str(STR) + '\n')
    file.write('#MAG' + '\n')
    file.write(str(MAG) + '\n')
    file.write('#SKL' + '\n')
    file.write(str(SKL) + '\n')
    file.write('#SPD' + '\n')
    file.write(str(SPD) + '\n')
    file.write('#LCK' + '\n')
    file.write(str(LCK) + '\n')
    file.write('#DEF' + '\n')
    file.write(str(DEF) + '\n')
    file.write('#RES' + '\n')
    file.write(str(RES) + '\n')
    file.write('#HP GROWTH' + '\n')
    file.write(str(HP_GROWTH) + '\n')
    file.write('#STR GROWTH' + '\n')
    file.write(str(STR_GROWTH) + '\n')
    file.write('#MAG GROWTH' + '\n')
    file.write(str(MAG_GROWTH) + '\n')
    file.write('#SKL GROWTH' + '\n')
    file.write(str(SKL_GROWTH) + '\n')
    file.write('#SPD GROWTH' + '\n')
    file.write(str(SPD_GROWTH) + '\n')
    file.write('#LCK GROWTH' + '\n')
    file.write(str(LCK_GROWTH) + '\n')
    file.write('#DEF GROWTH' + '\n')
    file.write(str(DEF_GROWTH) + '\n')
    file.write('#RES GROWTH' + '\n')
    file.write(str(RES_GROWTH) + '\n')
    file.write('#Gold' + '\n')
    file.write(str(GOLD) + '\n')
    file.write('#EXP' + '\n')
    file.write(str(EXP) + '\n')
    file.close

    time.sleep(1.5)
    os.system('cls')
    print('File Created')
    time.sleep(1.5)
    main_menu()
file_create()
